package main

import (
	"bytes"
	"encoding/binary"
	"errors"
	"log"
	"os"
	"os/signal"
	"syscall"

	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"
	"golang.org/x/sys/unix"
)

//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -tags linux bpf ringbuffer.c -- -I../headers

func main() {
	fn := "sys_execve"

	stopper := make(chan os.Signal, 1)
	signal.Notify(stopper, os.Interrupt, syscall.SIGTERM)

	// Allow the current process to lock memory for ebpf resource
	if err := rlimit.RemoveMemlock(); err != nil {
		log.Fatal(err)
	}

	// Load pre-compiled programs and maps into the kernel
	objs := bpfObjects{}

	if err := loadBpfObjects(&objs, nil); err != nil {
		log.Fatalf("loading objects: %v", err)
	}

	defer objs.Close()

	// Open a kprobe at the entry point of the kernel function and attach pre-compied bpf program
	// Each time the kernel function enters, the program will emit an event containing pid and comm of the received task
	kp, err := link.Kprobe(fn, objs.KprobeExecve, nil)
	if err != nil {
		log.Fatalf("opening kprobe: %s", err)
	}
	defer kp.Close()

	// Open a ring buffer reader from userspace RINGBUF map
	rd, err := ringbuf.NewReader(objs.Events)

	if err != nil {
		log.Fatalf("open ringbuf reader: %s", err)
	}

	defer rd.Close()

	// Close the reader when process receives signal, which will exit the read loop

	go func() {
		<-stopper
		if err := rd.Close(); err != nil {
			log.Fatalf("Closing ring buf reader: %s", err)
		}
	}()

	log.Println("waiting for events...")

	// bpfEvent is generated by bpf2go
	var event bpfEvent

	for {
		record, err := rd.Read()
		if err != nil {
			if errors.Is(err, ringbuf.ErrClosed) {
				log.Println("Received signal, exiting...")
				return
			}

			log.Printf("Reading from reader: %s", err)
			continue
		}

		// Parse the ringbuf event entry into bpfEvent struct
		if err := binary.Read(bytes.NewBuffer(record.RawSample), binary.LittleEndian, &event); err != nil {
			log.Printf("parsing ringbuf events: %s", err)
			continue
		}

		log.Printf("pid: %d\tcomm: %s\n", event.Pid, unix.ByteSliceToString(event.Comm[:]))
	}

}
