// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpfHist struct {
	Slots [26]uint32
	Comm  [16]int8
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	HandleSchedSwitch    *ebpf.ProgramSpec `ebpf:"handle_sched_switch"`
	HandleSchedWakeup    *ebpf.ProgramSpec `ebpf:"handle_sched_wakeup"`
	HandleSchedWakeupNew *ebpf.ProgramSpec `ebpf:"handle_sched_wakeup_new"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	CgroupMap *ebpf.MapSpec `ebpf:"cgroup_map"`
	Hists     *ebpf.MapSpec `ebpf:"hists"`
	Start     *ebpf.MapSpec `ebpf:"start"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
	FilterCg       *ebpf.VariableSpec `ebpf:"filter_cg"`
	TargMs         *ebpf.VariableSpec `ebpf:"targ_ms"`
	TargPerPidns   *ebpf.VariableSpec `ebpf:"targ_per_pidns"`
	TargPerProcess *ebpf.VariableSpec `ebpf:"targ_per_process"`
	TargPerThread  *ebpf.VariableSpec `ebpf:"targ_per_thread"`
	TargTgid       *ebpf.VariableSpec `ebpf:"targ_tgid"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	CgroupMap *ebpf.Map `ebpf:"cgroup_map"`
	Hists     *ebpf.Map `ebpf:"hists"`
	Start     *ebpf.Map `ebpf:"start"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.CgroupMap,
		m.Hists,
		m.Start,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
	FilterCg       *ebpf.Variable `ebpf:"filter_cg"`
	TargMs         *ebpf.Variable `ebpf:"targ_ms"`
	TargPerPidns   *ebpf.Variable `ebpf:"targ_per_pidns"`
	TargPerProcess *ebpf.Variable `ebpf:"targ_per_process"`
	TargPerThread  *ebpf.Variable `ebpf:"targ_per_thread"`
	TargTgid       *ebpf.Variable `ebpf:"targ_tgid"`
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	HandleSchedSwitch    *ebpf.Program `ebpf:"handle_sched_switch"`
	HandleSchedWakeup    *ebpf.Program `ebpf:"handle_sched_wakeup"`
	HandleSchedWakeupNew *ebpf.Program `ebpf:"handle_sched_wakeup_new"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.HandleSchedSwitch,
		p.HandleSchedWakeup,
		p.HandleSchedWakeupNew,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_x86_bpfel.o
var _BpfBytes []byte
